<?php
/**
 * Implements hook_node_info().
 */
function hf_advisories_node_info() {
  $items = array(
    'advisories' => array(
      'name' => t('Advisories'),
      'base' => 'node_content',
      'description' => t('Add an advisory to appear on the advisory listings page.'),
      'has_title' => '1',
      'title_label' => t('Advisory title'),
      'help' => '',
    ),
  );
  return $items;
}


/**
 * Implement hook_form()
 */
function hf_advisories_form($node, $form_state) {
    return node_content_form($node, $form_state);
}